name: PlatformIO CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: 1arp/create-a-file-action@0.2
      with:
        path: 'include'
        file: 'config.h'
        content: |
          #ifndef CONFIG_H
          #define CONFIG_H

          #define WIFI_SSID "DUMMY"
          #define WIFI_PW "DUMMY"

          #define MQTT_HOST IPAddress(10, 10, 10, 10)
          #define MQTT_PORT 10
          #define MQTT_USER "DUMMY"
          #define MQTT_PW "DUMMY"

          #define MQTT_BASE_TOPIC "DUMMY/DUMMY"

          #endif
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Build
      run: pio run --environment d1_mini_lite
    - name: Test
      run: pio test --environment native --verbose
